
# parameter for analysis of one individual
rat_type: "CHR"      # or CTRL 
rat_name: "#525"
bodypart: finger_3 
view: left           # camera view
task: L1            # L1: left lever, L2: right lever

# hyper parameters
threshold: 0.7
fps: 125
clip_length: 12.5       # sec
laser_on_duration: 0.3  # sec 
max_lost_coords: 10
frame_width_px: 512     # pixels

# parameter for inter rat analysis
inter_rat:
  rats: 
    - "#525"
    - "#521"

  contra_hemi: 
    "#517": "RightHemi"
    "#521": "LeftHemi"
    "#525": "RightHemi"


laser_intensities: 
  Beta: 
    - 2,5mW
    - 1mW
  Conti: 
    - 0,5mW
    - 0,75mW
  NOstim: 
    - NOstim
    - 0mW


paths:
  # input data
  model: "/media/filer2/T4b/UserFolders/Poemiti/Reaching-DLC-model-main/data/model/DLC-Poe-2026-03-27/"
  raw_videos: "/media/filer2/T4b/UserFolders/Raphael/Raphael_M2_2024/Opto_SkilledReaching_2024_experiments/MOVIES/"
  # raw_videos: "/media/filer2/T4b/Datasets/Rats/Photron_Video/Raphael2024"

  # output folder
  data_root: ./data
  database: "{data_root}/database"

  # inter rat
  inter_rat: "{data_root}/inter_rat"

  # per rat
  rat_root: "{data_root}/rat_{rat_name}"
  raw_clips: "{rat_root}/raw_clips"
  
  processed: "{rat_root}/processed"
  dlc: "{processed}/dlc"
  metrics: "{processed}/metrics"
  luminosity: "{processed}/luminosity"
  preprocessing: "{processed}/preprocessing"

  analysis: "{rat_root}/analysis_{bodypart}"
